# BUUSEC 2019 Sql Course 1

version: "2"

services:

  web:
    build: .
    image: glzjin/buusec_2019_sqli_labs
    restart: always
    ports:
      - "127.0.0.1:8302:80"
    environment:
      - FLAG=flag{glzjin_wants_a_girl_firend}
